import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {Script} from 'node:vm';
import {enqueueScalp,fillStrategy,sellLeg,manageTrend,tickStrategies,usableQuote,saveQuote,scalpExit,strategyThresholds,strategyEntryWindow,isolatedOverview,manualStrategyClose,trendSignal,trendIngest,validateTrendBars} from '../worker/strategy_engines.mjs';
import {ingest,riskIngest,geminiDecision,finalize} from '../worker/cloud_bridge.mjs';
const now=Date.parse('2026-10-09T12:00:00.000Z'),iso=t=>new Date(t).toISOString();const req=b=>new Request('https://example.test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
function database(){const dir=mkdtempSync(join(tmpdir(),'isolated-')),path=join(dir,'db.sqlite'),adapter=new URL('./funnel_sqlite.py',import.meta.url).pathname;const call=x=>JSON.parse(execFileSync('python3',[adapter,path],{input:JSON.stringify(x),encoding:'utf8'}));call({init:true});const db={prepare(sql){return {sql,params:[],bind(...p){this.params=p;return this;},async all(){return call({statements:[this]})[0];},async first(){return (await this.all()).results[0]||null;},async run(){return this.all();}};},async batch(s){return call({statements:s});}};return {db,clean:()=>rmSync(dir,{recursive:true,force:true})};}
async function risk(db,symbol){await db.prepare('INSERT OR REPLACE INTO bist_funnel_risk VALUES(?,1,?,?,?)').bind(symbol,iso(now-3600000),'2026-10-10T00:00:00.000Z','official').run();}
async function quote(db,symbol,price,time=now){await saveQuote(db,symbol,{symbol,price,quote_time:iso(time),source:'YAHOO_INDICATIVE'},time);}
async function scalpQueue(db,symbol,score=1,time=now){const key=symbol+':'+iso(now-900000),metrics=JSON.stringify({resistance:99,vwap:99});await risk(db,symbol);await db.prepare("INSERT OR IGNORE INTO bist_ai_decisions(signal_key,run_id,symbol,bar_time,model,status,reason,created_at,completed_at) VALUES(?,'test',?,?,'gpt-4o-mini','APPROVED','ok',?,?)").bind(key,symbol,iso(now-900000),iso(time),iso(time)).run();await db.prepare("INSERT OR IGNORE INTO bist_gemini_decisions VALUES(?,'test',?,?,'gemini-3.1-flash-lite','APPROVED',85,'ok',?)").bind(key,symbol,iso(now-900000),iso(time)).run();await db.prepare("INSERT OR IGNORE INTO scalp_sniper_queue VALUES(?,?,?,?,?,?,'READY','ok',?)").bind(key,symbol,iso(now-900000),iso(time),iso(time+900000),score,metrics).run();return key;}
async function trendFixture(db,symbol='ASTOR'){
 await risk(db,symbol);const hour=Array.from({length:220},(_,i)=>{const p=100+i*.05;return {time:iso(now-(220-i)*3600000),open:p-.1,high:p+.1,low:p-.2,close:p,volume:1e6};}),daily=Array.from({length:220},(_,i)=>{const p=75+i*.1;return {time:iso(now-(221-i)*86400000),open:p-.1,high:p+.1,low:p-.2,close:p,volume:1e6};});
 await db.prepare("INSERT INTO bist_bridge_bars VALUES(?,'15m',?,105,106,104,105,1000000,'YAHOO_INDICATIVE',?)").bind(symbol,iso(now-900000),iso(now)).run();await quote(db,symbol,111);
 const r=await trendIngest(req({symbol,source:'YAHOO_INDICATIVE',hour,daily,quote:{symbol,price:111,quote_time:iso(now),source:'YAHOO_INDICATIVE'}}),{DB:db},now);assert.equal(r.status,200);assert.equal((await r.json()).criteria_passed,true);return await db.prepare("SELECT * FROM virtual_trades WHERE strategy='SWING' AND status='OPEN' AND symbol=?").bind(symbol).first();
}
test('instant Scalp enters at approval-time quote; no N+1 wait, no backdated entry; retries preserve cash',async()=>{const {db,clean}=database();try{
 const symbol='TUPRS',old=Array.from({length:20},(_,i)=>({symbol,interval:'15m',time:iso(now-86400000+i*900000),open:99,high:100,low:98,close:99,volume:1e6})),bar={symbol,interval:'15m',time:iso(now-900000),open:100,high:104,low:100,close:103.5,volume:2e6};await risk(db,symbol);const env={DB:db,OPENAI_API_KEY:'unit-test-only'};
 await ingest(req({source:'YAHOO_INDICATIVE',feed_type:'INDICATIVE_INTRADAY',bars:[...old,bar],quote:{symbol,price:103.6,quote_time:iso(now),source:'YAHOO_INDICATIVE'},run_id:'instant',purpose:'HOT_CANDIDATE'}),env,now);
 await geminiDecision(req({run_id:'instant',symbol,bar_time:iso(now-900000),model:'gemini-3.1-flash-lite',status:'APPROVED',verdict:{approved:true,confidence:85,reason:'ok'}}),env,now);
 const ai=async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'{"onay":true,"neden":"ok","guven":85}'}}]}));
 await finalize(req({run_id:'instant'}),env,now,ai);const t=await db.prepare('SELECT * FROM virtual_trades').first();assert.ok(Date.parse(t.entry_time)>=now&&Date.parse(t.entry_time)<now+10000);assert.equal(t.entry_quote_time,iso(now));assert.equal(t.executed_price,103.6*1.002);assert.equal(t.strategy,'SCALP');assert.equal((await db.prepare("SELECT COUNT(*) n FROM virtual_trades WHERE strategy='SWING'").first()).n,0);
 const before=(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first()).available_cash;await finalize(req({run_id:'instant'}),env,now,ai);await tickStrategies(db,now);assert.equal((await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first()).available_cash,before);
 }finally{clean();}});
test('two capped slots in EACH motor, same symbol allowed across motors; highest queue refills only its own engine',async()=>{const {db,clean}=database();try{
 for(const [s,score] of [['ASTOR',10],['TUPRS',9],['REEDR',8],['BORLS',3]]){await scalpQueue(db,s,score);await quote(db,s,111);}
 await fillStrategy(db,'SCALP',now);const trend=await trendFixture(db,'ASTOR');const second=await trendFixture(db,'BINHO');assert.ok(trend&&second);
 let all=(await db.prepare("SELECT * FROM virtual_trades WHERE status='OPEN'").all()).results;assert.equal(all.length,4);assert.equal(all.filter(t=>t.symbol==='ASTOR').length,2);for(const t of all)assert.ok(t.executed_price*t.lot_count+t.commission<=1250);
 const scalp=all.find(t=>t.strategy==='SCALP'&&t.symbol==='ASTOR'),trendCash=await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first();await sellLeg(db,scalp,scalp.remaining_lots,115,'TP_NET_3',iso(now),now);await fillStrategy(db,'SCALP',now);assert.ok(await db.prepare("SELECT id FROM virtual_trades WHERE symbol='REEDR' AND strategy='SCALP' AND status='OPEN'").first());assert.deepEqual(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first(),trendCash);
 const remaining=(await db.prepare("SELECT * FROM virtual_trades WHERE status='OPEN'").all()).results;await assert.rejects(db.prepare("INSERT INTO virtual_trades SELECT NULL,strategy,'MORE',signal_price,executed_price,lot_count,commission,entry_time,NULL,NULL,NULL,NULL,'OPEN',1,'SCALP:more',2,remaining_lots,0,NULL,NULL,entry_quote_time,entry_observed_at,NULL FROM virtual_trades WHERE id=?").bind(remaining.find(t=>t.strategy==='SCALP').id).run(),/PAPER_SLOT_BUSY/);
 }finally{clean();}});
test('TP1 sells floor-half once, credits only Trend cash; remaining basis, fees, breakeven and final PnL reconcile',async()=>{const {db,clean}=database();try{
 const t=await trendFixture(db);assert.equal(t.lot_count,11);const scalpBefore=await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first();const baseline=(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first()).available_cash;
 const threshold=strategyThresholds(t);assert.equal(await sellLeg(db,t,Math.floor(t.lot_count/2),threshold.tp,'TREND_TP1',iso(now),now),true);assert.equal(await sellLeg(db,t,5,threshold.tp,'TREND_TP1',iso(now),now),false);
 let partial=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(partial.remaining_lots,6);assert.equal(partial.tp1_done,1);assert.equal(partial.status,'OPEN');assert.ok(partial.trailing_stop>=threshold.breakeven);const leg=await db.prepare('SELECT * FROM strategy_exit_legs').first();assert.ok(Math.abs(leg.pnl_net/((t.executed_price+t.commission/t.lot_count)*5)-.04)<1e-10);assert.ok(Math.abs((await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first()).available_cash-baseline-(leg.executed_price*5-leg.commission))<1e-8);
 assert.equal(await sellLeg(db,partial,6,threshold.breakeven,'TREND_TRAILING',iso(now+60000),now+60000),true);partial=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(partial.status,'CLOSED');assert.ok(Math.abs(partial.pnl_net-leg.pnl_net)<1e-8);const cash=(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first()).available_cash;assert.ok(Math.abs(cash-2500-partial.pnl_net)<1e-8);assert.deepEqual(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first(),scalpBefore);const overview=await isolatedOverview(db,now+60000);assert.equal(overview.realised_pnl,partial.pnl_net);assert.equal(overview.trend_slots,0);assert.equal(overview.exit_history.length,2);
 }finally{clean();}});
test('Scalp 15 minute expiry is fixed, stale quotes cannot fill, 17:40 closes Scalp but Trend remains overnight',async()=>{const {db,clean}=database();try{
 await scalpQueue(db,'TUPRS');await quote(db,'TUPRS',100,now-900001);assert.equal((await fillStrategy(db,'SCALP',now)).opened,0);await quote(db,'TUPRS',100);assert.equal((await fillStrategy(db,'SCALP',now+900000)).opened,0);assert.equal((await db.prepare('SELECT status FROM scalp_sniper_queue').first()).status,'EXPIRED');
 const eod=Date.parse('2026-10-09T14:40:00Z'),t=await trendFixture(db);await quote(db,t.symbol,111,eod);await scalpQueue(db,'REEDR',1,eod-5*60000);await quote(db,'REEDR',100,eod-5*60000);await fillStrategy(db,'SCALP',eod-5*60000);await quote(db,'REEDR',100,eod);await tickStrategies(db,eod);assert.equal((await db.prepare("SELECT status,exit_reason FROM virtual_trades WHERE strategy='SCALP'").first()).exit_reason,'SCALP_EOD_1740');assert.equal((await db.prepare("SELECT status FROM virtual_trades WHERE strategy='SWING'").first()).status,'OPEN');assert.equal(strategyEntryWindow('SCALP',eod),false);assert.equal(strategyEntryWindow('SWING',eod),true);
 }finally{clean();}});
test('scalp deadline precedes later TP; same candle ambiguity stops first; pre-entry high/low is ignored',()=>{const t={strategy:'SCALP',executed_price:100,lot_count:10,remaining_lots:10,commission:2,entry_time:iso(now)},b=(i,high=100.5,low=100)=>({bar_time:iso(now+i*900000),open:100,high,low,close:100.2});assert.equal(scalpExit(t,[b(0),b(1),b(2),b(3),b(4,120)],null,now+70*60000).reason,'TIME_EXIT');assert.equal(scalpExit(t,[b(0,120,90)],null,now+900000).reason,'SL_NET_1_5');assert.equal(scalpExit({...t,entry_time:iso(now+60000)},[b(0,120,90)],null,now+900000),null);});
test('Trend stop established at open wins before TP1; trailing uses only completed two-bar lows and never falls',async()=>{const {db,clean}=database();try{
 const t=await trendFixture(db);const time=iso(now),raw=[{time,open:111,high:122,low:109,close:120,volume:1e6},{time:iso(now+3600000),open:120,high:123,low:119,close:122,volume:1e6}];await db.prepare("INSERT INTO trend_bars SELECT 'ASTOR','60m',json_extract(value,'$.time'),json_extract(value,'$.open'),json_extract(value,'$.high'),json_extract(value,'$.low'),json_extract(value,'$.close'),json_extract(value,'$.volume'),'YAHOO_INDICATIVE',? FROM json_each(?)").bind(iso(now+7200000),JSON.stringify(raw)).run();await manageTrend(db,now+7200000);let closed=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(closed.status,'CLOSED');assert.equal(closed.tp1_done,0);assert.equal((await db.prepare('SELECT COUNT(*) n FROM strategy_exit_legs').first()).n,1);
 }finally{clean();}});
test('invalid Trend data, missing EMA200 and no provider quote fail closed; Worker auth + UI scripts compile',async()=>{
 assert.throws(()=>validateTrendBars('ASTOR','60m',[{time:iso(now),open:100,high:101,low:99,close:100,volume:1}],now));assert.equal(trendSignal([],[],[],now),null);assert.equal(usableQuote({price:100,quote_time:iso(now),source:'EOD'},now),false);
 const code=readFileSync(new URL('../worker/index.js',import.meta.url),'utf8'),{default:worker}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));for(const path of ['/bist/feed/trend','/bist/feed/quote','/bist/strategy/close'])assert.equal((await worker.fetch(new Request('https://example.test'+path,{method:'POST'}),{ACCESS_TOKEN:'test'})).status,401);
 const html=await (await worker.fetch(new Request('https://example.test/'),{})).text();for(const script of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Script(script[1]);for(const id of ['scalpRoom','trendRoom','scalpQueue','trendQueue','historyRows'])assert.ok(html.includes('id="'+id+'"'));
});

test('post TP1 two completed lows ratchet stop; later gap sells only the remainder',async()=>{const {db,clean}=database();try{
 const t=await trendFixture(db);const bars=[{time:iso(now),open:111,high:122,low:110.8,close:120,volume:1e6},{time:iso(now+3600000),open:120,high:123,low:119,close:122,volume:1e6},{time:iso(now+7200000),open:122,high:124,low:120,close:123,volume:1e6}];
 await db.prepare("INSERT INTO trend_bars SELECT 'ASTOR','60m',json_extract(value,'$.time'),json_extract(value,'$.open'),json_extract(value,'$.high'),json_extract(value,'$.low'),json_extract(value,'$.close'),json_extract(value,'$.volume'),'YAHOO_INDICATIVE',? FROM json_each(?)").bind(iso(now+10800000),JSON.stringify(bars)).run();await manageTrend(db,now+10800000);let state=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(state.tp1_done,1);assert.equal(state.remaining_lots,6);assert.equal(state.trailing_stop,119);assert.equal(state.status,'OPEN');
 await db.prepare("INSERT INTO trend_bars VALUES('ASTOR','60m',?,118,121,116,119,1000000,'YAHOO_INDICATIVE',?)").bind(iso(now+10800000),iso(now+14400000)).run();await manageTrend(db,now+14400000);state=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(state.status,'CLOSED');assert.equal(state.exit_reason,'TREND_TRAILING');assert.equal(state.exit_price,118*.998);assert.equal((await db.prepare('SELECT COUNT(*) n FROM strategy_exit_legs').first()).n,2);assert.equal((await manageTrend(db,now+14400000)).closed,0);
 }finally{clean();}});
test('Trend holds across sessions and exits after five completed trading sessions, not at EOD',async()=>{const {db,clean}=database();try{
 const t=await trendFixture(db),future=Date.parse('2026-10-16T12:00:00Z');for(const date of ['2026-10-09','2026-10-12','2026-10-13','2026-10-14','2026-10-15'])await db.prepare("INSERT OR IGNORE INTO trend_bars VALUES('ASTOR','1d',?,111,112,110,111,1000000,'YAHOO_INDICATIVE',?)").bind(date+'T07:00:00.000Z',iso(future)).run();await quote(db,'ASTOR',111,future);const result=await manageTrend(db,future);assert.equal(result.closed,1);assert.equal((await db.prepare('SELECT exit_reason FROM virtual_trades WHERE id=?').bind(t.id).first()).exit_reason,'TREND_MAX_5_SESSIONS');
 }finally{clean();}});
test('manual close requires fresh server price, immediately refills the correct queue and is retry safe',async()=>{const {db,clean}=database();try{
 for(const [s,p] of [['TUPRS',10],['ASTOR',9],['REEDR',8]]){await scalpQueue(db,s,p);await quote(db,s,100);}await fillStrategy(db,'SCALP',now);const t=await db.prepare("SELECT * FROM virtual_trades WHERE symbol='TUPRS'").first();const result=await (await manualStrategyClose(req({trade_id:t.id,strategy:'SCALP'}),{DB:db},now)).json();assert.equal(result.ok,true);assert.equal(result.refill.opened,1);assert.equal((await manualStrategyClose(req({trade_id:t.id,strategy:'SCALP'}),{DB:db},now)).status,409);assert.equal((await manualStrategyClose(req({trade_id:t.id,strategy:'SWING'}),{DB:db},now)).status,409);const cash=(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first()).available_cash;await tickStrategies(db,now);assert.equal((await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first()).available_cash,cash);
 }finally{clean();}});

test('fresh READY Trend queue prefers berker3 and expired EOD rows cannot enter',async()=>{const {db,clean}=database();try{
 const a=await trendFixture(db,'TUPRS'),b=await trendFixture(db,'REEDR');for(const t of [a,b])await sellLeg(db,t,t.remaining_lots,111,'MANUAL_CLOSE',iso(now),now);
 for(const [symbol,priority,score] of [['TUPRS',0,100],['REEDR',1,1]]){const original=await db.prepare('SELECT * FROM trend_radar_queue WHERE symbol=?').bind(symbol).first();await db.prepare("INSERT INTO trend_radar_queue VALUES(?,?,?,?,?,?,?,'READY','priority test',?)").bind(symbol+':new',symbol,original.bar_time,iso(now),iso(now+3600000),score,priority,original.metrics_json).run();}
 const cash=(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first()).available_cash;await db.prepare("UPDATE paper_cash_accounts SET available_cash=1200 WHERE strategy='SWING'").run();await fillStrategy(db,'SWING',now);assert.equal((await db.prepare("SELECT symbol FROM virtual_trades WHERE strategy='SWING' AND status='OPEN'").first()).symbol,'REEDR');await fillStrategy(db,'SWING',now+3600000);assert.equal((await db.prepare("SELECT status FROM trend_radar_queue WHERE signal_key='TUPRS:new'").first()).status,'EXPIRED');
 }finally{clean();}});

test('Scalp Runner partial sale locks profit once, retains slot past 60min, then net BE closes only remainder',async()=>{const {db,clean}=database();try{
 await scalpQueue(db,'TUPRS');await quote(db,'TUPRS',100);await fillStrategy(db,'SCALP',now);let t=await db.prepare("SELECT * FROM virtual_trades WHERE strategy='SCALP'").first();const levels=strategyThresholds(t),qty=Math.floor(t.lot_count*.7),trendCash=await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first();
 await quote(db,'TUPRS',levels.tp,now+60000);let result=await tickStrategies(db,now+60000);assert.equal(result.scalp.partial,1);assert.equal(result.scalp.closed,0);t=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(t.tp1_done,1);assert.equal(t.remaining_lots,t.lot_count-qty);assert.equal(t.status,'OPEN');assert.equal(t.scalp_runner_started_at,iso(now+60000));assert.equal(t.trailing_stop,levels.breakeven);const leg=await db.prepare('SELECT * FROM strategy_exit_legs').first();assert.ok(Math.abs(leg.pnl_net/((t.executed_price+t.commission/t.lot_count)*qty)-.03)<1e-10);
 await tickStrategies(db,now+60000);assert.equal((await db.prepare('SELECT COUNT(*) n FROM strategy_exit_legs').first()).n,1);
 await quote(db,'TUPRS',levels.tp+1,now+70*60000);assert.equal((await tickStrategies(db,now+70*60000)).scalp.closed,0);assert.equal((await isolatedOverview(db,now+70*60000)).scalp_slots,1);
 await quote(db,'TUPRS',levels.breakeven,now+71*60000);assert.equal((await tickStrategies(db,now+71*60000)).scalp.closed,1);t=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(t.exit_reason,'SCALP_RUNNER_BE');assert.ok(Math.abs(t.pnl_net-leg.pnl_net)<1e-8);assert.ok(Math.abs((await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SCALP'").first()).available_cash-2500-t.pnl_net)<1e-8);assert.deepEqual(await db.prepare("SELECT available_cash FROM paper_cash_accounts WHERE strategy='SWING'").first(),trendCash);
 }finally{clean();}});
test('Scalp Runner historical TP1 does not retroactively stop on same bar; next bar stop and EOD liquidate remainder',()=>{
 const t={strategy:'SCALP',executed_price:100,lot_count:100,remaining_lots:100,tp1_done:0,commission:20,entry_time:iso(now)},levels=strategyThresholds(t),bar={bar_time:iso(now),open:101,high:105,low:100,close:104};const tp=scalpExit(t,[bar],null,now+900000);assert.equal(tp.reason,'SCALP_TP1');assert.equal(tp.qty,70);assert.equal(tp.activation,iso(now+900000));const runner={...t,tp1_done:1,remaining_lots:30,scalp_runner_started_at:tp.activation};assert.equal(scalpExit(runner,[bar],null,now+900000),null);
 const next={...bar,bar_time:iso(now+900000),open:104,low:levels.breakeven};assert.equal(scalpExit(runner,[bar,next],null,now+1800000).reason,'SCALP_RUNNER_BE');const eod=Date.parse('2026-10-09T14:40:00Z');const q={source:'YAHOO_INDICATIVE',price:109.9,quote_time:iso(eod)};assert.equal(scalpExit(runner,[],q,eod).reason,'SCALP_RUNNER_EOD');assert.equal(scalpExit(runner,[],{...q,quote_time:iso(eod-60000)},eod),null);
});
test('Scalp Runner EOD accounting sells remaining lots; initial stop still exits all and invalid partial cannot pass D1',async()=>{const {db,clean}=database();try{
 await scalpQueue(db,'TUPRS');await quote(db,'TUPRS',100);await fillStrategy(db,'SCALP',now);let t=await db.prepare("SELECT * FROM virtual_trades WHERE strategy='SCALP'").first();const level=strategyThresholds(t);
 await assert.rejects(sellLeg(db,t,Math.floor(t.lot_count/2),level.tp,'SCALP_TP1',iso(now),now,iso(now)),/INVALID_SCALP_TP1/);
 await quote(db,t.symbol,level.tp,now+60000);await tickStrategies(db,now+60000);const eod=Date.parse('2026-10-09T14:40:00Z');await quote(db,t.symbol,110,eod);assert.equal((await tickStrategies(db,eod)).scalp.closed,1);t=await db.prepare('SELECT * FROM virtual_trades WHERE id=?').bind(t.id).first();assert.equal(t.exit_reason,'SCALP_RUNNER_EOD');assert.equal(t.remaining_lots,0);assert.equal((await db.prepare('SELECT SUM(qty) qty FROM strategy_exit_legs').first()).qty,t.lot_count);
 }finally{clean();}});
