-- Yahoo paper feed: 15-minute delay + up to 5-minute transport tolerance. Queue TTL remains 15 minutes.
DROP TRIGGER cloud_paper_entry_guard;
CREATE TRIGGER cloud_paper_entry_guard BEFORE INSERT ON virtual_trades WHEN NEW.engine_version=2 OR NEW.feed_entry_key IS NOT NULL BEGIN
 SELECT CASE WHEN NEW.engine_version!=2 OR NEW.strategy NOT IN('SCALP','SWING') OR NEW.status!='OPEN' OR NEW.slot_id NOT IN(1,2) OR COALESCE(NEW.remaining_lots,0)!=NEW.lot_count OR NEW.lot_count<CASE WHEN NEW.strategy='SWING' THEN 2 ELSE 1 END OR NEW.entry_observed_at IS NULL OR NEW.entry_quote_time IS NULL THEN RAISE(ABORT,'PAPER_INVALID_ENTRY') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM virtual_trades WHERE strategy=NEW.strategy AND status='OPEN' AND (slot_id=NEW.slot_id OR symbol=NEW.symbol)) OR (SELECT COUNT(*) FROM virtual_trades WHERE strategy=NEW.strategy AND status='OPEN')>=2 THEN RAISE(ABORT,'PAPER_SLOT_BUSY') END;
 SELECT CASE WHEN NEW.executed_price*NEW.lot_count+NEW.commission>1250.000001 OR NOT EXISTS(SELECT 1 FROM paper_cash_accounts WHERE strategy=NEW.strategy AND available_cash>=NEW.executed_price*NEW.lot_count+NEW.commission) THEN RAISE(ABORT,'PAPER_INSUFFICIENT_CASH') END;
 SELECT CASE WHEN (NEW.strategy='SCALP' AND NOT EXISTS(SELECT 1 FROM scalp_sniper_queue WHERE 'SCALP:'||signal_key=NEW.feed_entry_key AND status='READY' AND observed_at<=NEW.entry_time AND expires_at>NEW.entry_time)) OR (NEW.strategy='SWING' AND NOT EXISTS(SELECT 1 FROM trend_radar_queue WHERE 'TREND:'||signal_key=NEW.feed_entry_key AND status='READY' AND observed_at<=NEW.entry_time AND expires_at>NEW.entry_time)) THEN RAISE(ABORT,'PAPER_SIGNAL_NOT_ELIGIBLE') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM bist_funnel_risk WHERE symbol=NEW.symbol AND eligible=1 AND valid_until>NEW.entry_time) OR NOT EXISTS(SELECT 1 FROM strategy_quotes WHERE symbol=NEW.symbol AND quote_time=NEW.entry_quote_time AND julianday(quote_time)<=julianday(NEW.entry_time) AND julianday(quote_time)>=julianday(NEW.entry_time)-20.0/1440 AND date(quote_time,'+3 hours')=date(NEW.entry_time,'+3 hours') AND ABS(price*1.002-NEW.executed_price)<0.000001) THEN RAISE(ABORT,'PAPER_QUOTE_OR_RISK_INVALID') END;
END;
