const {test}=require('node:test');const assert=require('node:assert/strict');const {readFileSync}=require('node:fs');const {JSDOM}=require('jsdom');
test('PWA renders isolated rooms, partial exit history, live countdown and server-only manual close',async()=>{
 const html=readFileSync(require('node:path').join(__dirname,'../../worker/dashboard.html'),'utf8'),now=Date.parse('2026-10-09T13:00:00Z');let state={server_time:new Date(now).toISOString(),last_scan_at:new Date(now).toISOString(),last_scan_fetched:530,total_capital:5000,equity:5010,realised_pnl:20,scalp_cash:1250,swing_cash:1500,scalp_slots:1,trend_slots:1,scanner_live:true,scalp_sniper_queue:[{symbol:'REEDR',score:5,reason:'READY',expires_at:new Date(now+60000).toISOString()}],trend_radar_queue:[{symbol:'BINHO',score:3,priority:1,reason:'READY',expires_at:new Date(now+60000).toISOString()}],open_trades:[{id:1,symbol:'TUPRS',strategy:'SCALP',slot_id:1,lot_count:10,remaining_lots:10,executed_price:100,current_price:101,quote_time:new Date(now).toISOString(),entry_time:new Date(now-25*60000).toISOString(),quote_fresh:true,unrealised_pct:1,unrealised_net:10,thresholds:{tp:103,sl:98.5}},{id:2,symbol:'ASTOR<img src=x>',strategy:'SWING',slot_id:1,lot_count:11,remaining_lots:6,tp1_done:1,trailing_stop:104,executed_price:100,current_price:110,quote_time:new Date(now).toISOString(),entry_time:new Date(now-86400000).toISOString(),quote_fresh:true,unrealised_pct:10,unrealised_net:60,thresholds:{tp:104,sl:98.5}}],exit_history:[{symbol:'ASTOR',strategy:'SWING',qty:5,reason:'TREND_TP1',pnl_net:20,executed_price:104,observed_at:new Date(now).toISOString()},{symbol:'TUPRS',strategy:'SCALP',qty:10,reason:'TIME_EXIT',pnl_net:-1,executed_price:99,observed_at:new Date(now).toISOString()}]};
 const calls=[],copied=[];const dom=new JSDOM(html,{url:'https://panel.test/',runScripts:'dangerously',beforeParse(w){Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>copied.push(text)}});w.fetch=async(path,opts)=>{calls.push([path,opts]);if(path==='/bist/overview')return new Response(JSON.stringify(state));if(path==='/bist/connections')return new Response(JSON.stringify({gemini:{connection:'CONNECTED'},openai:{connection:'CONNECTED'}}));if(path==='/bist/strategy/berker3')return new Response(JSON.stringify({symbols:['ASTOR','REEDR']}));if(path==='/bist/strategy/close'){state={...state,open_trades:state.open_trades.filter(t=>t.id!==1),scalp_slots:0};return new Response(JSON.stringify({ok:true}));}throw Error('Unexpected endpoint');};}});
 try{const w=dom.window;await new Promise(r=>setTimeout(r,50));const doc=w.document;
  assert.match(doc.getElementById('scalpOpen').textContent,/TUPRS/);assert.doesNotMatch(doc.getElementById('scalpOpen').textContent,/ASTOR/);assert.match(doc.getElementById('trendOpen').textContent,/TP1 alındı.*6\/11/);assert.equal(doc.getElementById('trendOpen').querySelectorAll('img').length,0);assert.match(doc.getElementById('scalpOpen').textContent,/25\/60 dk/);assert.match(doc.getElementById('scalpQueue').textContent,/REEDR/);assert.doesNotMatch(doc.getElementById('scalpQueue').textContent,/BINHO/);
  assert.match(doc.getElementById('scalpOpen').textContent,/Emir Kurulum Kartı/);assert.match(doc.getElementById('scalpOpen').textContent,/7\/10 lot/);const copyButtons=[...doc.querySelectorAll('#scalpOpen button')].filter(b=>b.textContent.includes('Kopyala'));for(const b of copyButtons)b.click();await new Promise(r=>setTimeout(r,10));assert.deepEqual(copied,['100','98,5','103']);
  state={...state,open_trades:state.open_trades.map(t=>t.id===1?{...t,tp1_done:1,remaining_lots:3,thresholds:{...t.thresholds,breakeven:100.6}}:t)};await w.eval('refresh()');assert.match(doc.getElementById('scalpOpen').textContent,/Runner aktif · 3 lot/);assert.match(doc.getElementById('scalpOpen').textContent,/17:40’a kalan/);assert.doesNotMatch(doc.getElementById('scalpOpen').textContent,/25\/60 dk/);
  doc.querySelector('[data-filter="SWING"]').click();assert.match(doc.getElementById('historyRows').textContent,/TREND_TP1/);assert.doesNotMatch(doc.getElementById('historyRows').textContent,/TIME_EXIT/);
  doc.querySelector('#scalpOpen button').click();await new Promise(r=>setTimeout(r,50));const close=calls.find(x=>x[0]==='/bist/strategy/close');assert.deepEqual(JSON.parse(close[1].body),{trade_id:1,strategy:'SCALP'});assert.match(doc.getElementById('scalpOpen').textContent,/boş/);assert.match(doc.getElementById('trendOpen').textContent,/ASTOR/);
 }finally{dom.window.close();}
});
